name: Release
on:
  push:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_TAG: latest
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Set Env
        if: env.BRANCH_NAME != 'main'
        run: echo "IMAGE_TAG=$(echo ${BRANCH_NAME} | tr / - | tr \# - )" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ismdeep
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker release
        run: |
          set -eu
          docker buildx build --progress plain --platform linux/amd64 --pull --push -t ismdeep/syslog:${IMAGE_TAG} .
          echo "----------------------------------------------------------------------"
          echo "ismdeep/syslog:${IMAGE_TAG}"
          echo "----------------------------------------------------------------------"